name: Publish Python package to PyPI

on:
  push:
    branches:
      - main  # Adjust this if your default branch has a different name, like 'master'.

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pybuilder
          pyb install_dependencies
      - name: Build and package
        run: |
          pyb
